import re
import calendar

RE_TOWNS = {
    'Москва': re.compile(r'\bмоскв[ауы]\b'),
    'Лондон': re.compile(r'\bлондон[ае]{,1}\b'),
    'Париж': re.compile(r'\bпариж[ае]{,1}\b'),
    'Берлин': re.compile(r'\bберлин[ае]{,1}\b'),
    'Владивосток': re.compile(r'\bвладивосток[ае]{,1}\b'),
    'Минеральные воды': re.compile(r'\b(минеральные|мин)\sводы\b'),
    'Токио': re.compile(r'\bтокио\b'),
    'Пекин': re.compile(r'\bпекин[ае]{,1}\b')
}

ALL_POSSIBLE_FLIGHTS = {
    'Москва': {'Лондон': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                          {'hours': 15, 'minutes': 15}],
                                        calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                          'month_days': {
                              5: [{'hours': 5, 'minutes': 15},
                                  {'hours': 5, 'minutes': 45}],
                              15: [{'hours': 15, 'minutes': 5},
                                   {'hours': 5, 'minutes': 15}],
                              25: [{'hours': 5, 'minutes': 25},
                                   {'hours': 15, 'minutes': 35},
                                   {'hours': 15, 'minutes': 45}]},
                          'charter': ['25-05-2021 17:00', '15-05-2020 17:00']},
               'Париж': {'week_days': {calendar.THURSDAY: [{'hours': 15, 'minutes': 30},
                                                           {'hours': 18, 'minutes': 30}],
                                       calendar.FRIDAY: [{'hours': 13, 'minutes': 30}]},
                         'month_days': {
                             6: [{'hours': 10, 'minutes': 0},
                                 {'hours': 11, 'minutes': 0}],
                             16: [{'hours': 12, 'minutes': 0},
                                  {'hours': 13, 'minutes': 0}],
                             26: [{'hours': 14, 'minutes': 0},
                                  {'hours': 15, 'minutes': 0},
                                  {'hours': 16, 'minutes': 0}]},
                         'charter': ['26-05-2019 17:00', '26-05-2020 17:00']},
               'Берлин': {'week_days': {calendar.THURSDAY: [{'hours': 15, 'minutes': 30},
                                                            {'hours': 18, 'minutes': 30}],
                                        calendar.FRIDAY: [{'hours': 13, 'minutes': 30}]},
                          'month_days': {
                              7: [{'hours': 0, 'minutes': 0},
                                  {'hours': 1, 'minutes': 0}],
                              17: [{'hours': 2, 'minutes': 0},
                                   {'hours': 3, 'minutes': 0}],
                              27: [{'hours': 4, 'minutes': 0},
                                   {'hours': 5, 'minutes': 0},
                                   {'hours': 6, 'minutes': 0}]},
                          'charter': ['26-06-2019 17:00', '27-07-2020 17:00']},
               'Владивосток': {'week_days': {calendar.THURSDAY: [{'hours': 15, 'minutes': 30},
                                                                 {'hours': 18, 'minutes': 30}],
                                             calendar.FRIDAY: [{'hours': 13, 'minutes': 30}]},
                               'month_days': {
                                   7: [{'hours': 0, 'minutes': 0},
                                       {'hours': 1, 'minutes': 0}],
                                   17: [{'hours': 2, 'minutes': 0},
                                        {'hours': 3, 'minutes': 0}],
                                   27: [{'hours': 4, 'minutes': 0},
                                        {'hours': 5, 'minutes': 0},
                                        {'hours': 6, 'minutes': 0}]},
                               'charter': ['26-06-2019 17:00', '27-07-2020 17:00']},
               'Минеральные воды': {'week_days': {calendar.THURSDAY: [{'hours': 15, 'minutes': 36},
                                                                      {'hours': 18, 'minutes': 45}],
                                                  calendar.FRIDAY: [{'hours': 13, 'minutes': 32}]},
                                    'month_days': {
                                        9: [{'hours': 0, 'minutes': 1},
                                            {'hours': 1, 'minutes': 2}],
                                        19: [{'hours': 2, 'minutes': 3},
                                             {'hours': 3, 'minutes': 4}],
                                        20: [{'hours': 4, 'minutes': 5},
                                             {'hours': 5, 'minutes': 6},
                                             {'hours': 6, 'minutes': 7}]},
                                    'charter': ['26-06-2019 17:00', '27-07-2020 17:00']}
               },
    'Лондон': {'Париж': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                         {'hours': 15, 'minutes': 15}],
                                       calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                         'month_days': {
                             5: [{'hours': 5, 'minutes': 15},
                                 {'hours': 5, 'minutes': 45}],
                             15: [{'hours': 15, 'minutes': 5},
                                  {'hours': 5, 'minutes': 15}],
                             25: [{'hours': 5, 'minutes': 25},
                                  {'hours': 15, 'minutes': 35},
                                  {'hours': 15, 'minutes': 45}]},
                         'charter': ['25-05-2021 17:00', '15-05-2020 17:00']},
               'Берлин': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                          {'hours': 15, 'minutes': 15}],
                                        calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                          'month_days': {
                              5: [{'hours': 5, 'minutes': 15},
                                  {'hours': 5, 'minutes': 45}],
                              15: [{'hours': 15, 'minutes': 5},
                                   {'hours': 5, 'minutes': 15}],
                              25: [{'hours': 5, 'minutes': 25},
                                   {'hours': 15, 'minutes': 35},
                                   {'hours': 15, 'minutes': 45}]},
                          'charter': ['25-05-2021 17:00', '15-05-2020 17:00']},
               'Москва': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                          {'hours': 15, 'minutes': 15}],
                                        calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                          'month_days': {
                              5: [{'hours': 5, 'minutes': 15},
                                  {'hours': 5, 'minutes': 45}],
                              15: [{'hours': 15, 'minutes': 5},
                                   {'hours': 5, 'minutes': 15}],
                              25: [{'hours': 5, 'minutes': 25},
                                   {'hours': 15, 'minutes': 35},
                                   {'hours': 15, 'minutes': 45}]},
                          'charter': ['25-05-2021 17:00', '15-05-2020 17:00']}
               },
    'Париж': {'Москва': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                         {'hours': 15, 'minutes': 15}],
                                       calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                         'month_days': {
                             5: [{'hours': 5, 'minutes': 15},
                                 {'hours': 5, 'minutes': 45}],
                             15: [{'hours': 15, 'minutes': 5},
                                  {'hours': 5, 'minutes': 15}],
                             25: [{'hours': 5, 'minutes': 25},
                                  {'hours': 15, 'minutes': 35},
                                  {'hours': 15, 'minutes': 45}]},
                         'charter': ['25-05-2021 17:00', '15-05-2020 17:00']},
              'Лондон': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                         {'hours': 15, 'minutes': 15}],
                                       calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                         'month_days': {
                             5: [{'hours': 5, 'minutes': 15},
                                 {'hours': 5, 'minutes': 45}],
                             15: [{'hours': 15, 'minutes': 5},
                                  {'hours': 5, 'minutes': 15}],
                             25: [{'hours': 5, 'minutes': 25},
                                  {'hours': 15, 'minutes': 35},
                                  {'hours': 15, 'minutes': 45}]},
                         'charter': ['25-05-2021 17:00', '15-05-2020 17:00']},
              'Берлин': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                         {'hours': 15, 'minutes': 15}],
                                       calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                         'month_days': {
                             5: [{'hours': 5, 'minutes': 15},
                                 {'hours': 5, 'minutes': 45}],
                             15: [{'hours': 15, 'minutes': 5},
                                  {'hours': 5, 'minutes': 15}],
                             25: [{'hours': 5, 'minutes': 25},
                                  {'hours': 15, 'minutes': 35},
                                  {'hours': 15, 'minutes': 45}]},
                         'charter': ['25-05-2021 17:00', '15-05-2020 17:00']},
              'Владивосток': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                              {'hours': 15, 'minutes': 15}],
                                            calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                              'month_days': {
                                  5: [{'hours': 5, 'minutes': 15},
                                      {'hours': 5, 'minutes': 45}],
                                  15: [{'hours': 15, 'minutes': 5},
                                       {'hours': 5, 'minutes': 15}],
                                  25: [{'hours': 5, 'minutes': 25},
                                       {'hours': 15, 'minutes': 35},
                                       {'hours': 15, 'minutes': 45}]},
                              'charter': ['25-05-2021 17:00', '15-05-2020 17:00']}
              },
    'Берлин': {'Лондон': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                          {'hours': 15, 'minutes': 15}],
                                        calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                          'month_days': {
                              5: [{'hours': 5, 'minutes': 15},
                                  {'hours': 5, 'minutes': 45}],
                              15: [{'hours': 15, 'minutes': 5},
                                   {'hours': 5, 'minutes': 15}],
                              25: [{'hours': 5, 'minutes': 25},
                                   {'hours': 15, 'minutes': 35},
                                   {'hours': 15, 'minutes': 45}]},
                          'charter': ['25-05-2021 17:00', '15-05-2020 17:00']},
               'Париж': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                         {'hours': 15, 'minutes': 15}],
                                       calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                         'month_days': {
                             5: [{'hours': 5, 'minutes': 15},
                                 {'hours': 5, 'minutes': 45}],
                             15: [{'hours': 15, 'minutes': 5},
                                  {'hours': 5, 'minutes': 15}],
                             25: [{'hours': 5, 'minutes': 25},
                                  {'hours': 15, 'minutes': 35},
                                  {'hours': 15, 'minutes': 45}]},
                         'charter': ['25-05-2021 17:00', '15-05-2020 17:00']}},
    'Владивосток': {'Москва': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                               {'hours': 15, 'minutes': 15}],
                                             calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                               'month_days': {
                                   5: [{'hours': 5, 'minutes': 15},
                                       {'hours': 5, 'minutes': 45}],
                                   15: [{'hours': 15, 'minutes': 5},
                                        {'hours': 5, 'minutes': 15}],
                                   25: [{'hours': 5, 'minutes': 25},
                                        {'hours': 15, 'minutes': 35},
                                        {'hours': 15, 'minutes': 45}]},
                               'charter': ['25-05-2021 17:00', '15-05-2020 17:00']},
                    'Токио': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                              {'hours': 15, 'minutes': 15}],
                                            calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                              'month_days': {
                                  5: [{'hours': 5, 'minutes': 15},
                                      {'hours': 5, 'minutes': 45}],
                                  15: [{'hours': 15, 'minutes': 5},
                                       {'hours': 5, 'minutes': 15}],
                                  25: [{'hours': 5, 'minutes': 25},
                                       {'hours': 15, 'minutes': 35},
                                       {'hours': 15, 'minutes': 45}]},
                              'charter': ['25-05-2021 17:00', '15-05-2020 17:00']},
                    'Пекин': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                              {'hours': 15, 'minutes': 15}],
                                            calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                              'month_days': {
                                  5: [{'hours': 5, 'minutes': 15},
                                      {'hours': 5, 'minutes': 45}],
                                  15: [{'hours': 15, 'minutes': 5},
                                       {'hours': 5, 'minutes': 15}],
                                  25: [{'hours': 5, 'minutes': 25},
                                       {'hours': 15, 'minutes': 35},
                                       {'hours': 15, 'minutes': 45}]}}},
    'Минеральные воды': {'Москва': {'week_days': {calendar.MONDAY: [{'hours': 5, 'minutes': 5},
                                                                    {'hours': 15, 'minutes': 15}],
                                                  calendar.FRIDAY: [{'hours': 15, 'minutes': 25}]},
                                    'charter': ['25-05-2021 17:00', '15-05-2020 17:00']}
                         }
}


towns_departures = ''
towns_arrival = ''
for town in ALL_POSSIBLE_FLIGHTS:
    towns_departures += f'{town}, '
for town in RE_TOWNS:
    towns_arrival += f'{town}, '
